workspace(name = "test_ws")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_android",
    sha256 = "cd06d15dd8bb59926e4d65f9003bfc20f9da4b2519985c27e190cddc8b7a7806",
    strip_prefix = "rules_android-0.1.1",
    url = "https://github.com/bazelbuild/rules_android/archive/v0.1.1.zip",
)
load("@rules_android//rules:rules.bzl", "android_sdk_repository")
android_sdk_repository(name = "androidsdk", api_level=34)
register_toolchains("@androidsdk//:all")
